app:
  url: http://172.24.1.33:3000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Projet_GL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Projet_GL
    password: X*3EokAdn5GQVANe
